### ISSUE TITLE
test module is not packaged

### ISSUE THREAD

**Issue by frispete** [boppreh/simplecrypto#5]
As a packager, I'm usually running unit tests for every packaging.

Ah, I see, tests work for python3 only. :(

Let me know, if you're planning to change the situation.

**Comment by boppreh** [comment]
Simplecrypto now packages the `tests` module.

I've migrated to Python 3 years ago, and the `bytes` <-> `str` incompatibility is specially hard hitting on some of the modules (`formats`, for example). So sorry, but I don't have plans to backport the tests to Python 2. However, I'll be thankful if somebody does it and submits a PR.
